### ISSUE TITLE
Feature Request: Loading Data Files

### ISSUE THREAD

**Issue by ossie-git** [fugue/fregot#205]
Hi,

Just ran into Fregot and really like it. Although you can currently load input using :input and load a rego file, it would be great if you could tell it to load a data file. Is this currently planned? Thanks

**Comment by jaspervdj-luminal** [comment]
Hi @ossie-git, thanks for reporting!  This sounds relatively easy to add.  Just to be clear -- can you confirm that you mean loading a data file by using something like:

    :load path/to/file.yaml

Or:

    :load path/to/file.json

**Comment by ossie-git** [comment]
Hi @jaspervdj-luminal Exactly. It would be great if you can load in a data file (and possibly namespace it) so your rego files work exactly as they would in production (any import lines or full lines: data.managers... in your rego would point to the loaded data files)

**Comment by jaspervdj-luminal** [comment]
I added loading data files in #210.  Namespacing is not yet supported, I'll do that in a follow-up PR.

**Comment by jaspervdj-luminal** [comment]
I've added namespacing with support for the same syntax that OPA uses (`:load foo.bar:data.json` to load it into the `foo.bar` package name) in #211.  This will be in the next release.

**Comment by ossie-git** [comment]
Will definitely check it out. Thanks
