### ISSUE TITLE
Unable to test rule which returns a set due to unknown_variable issues

### ISSUE THREAD

**Issue by ahmedtalhakhan** [fugue/fregot#233]
Trying fregot for the first time and running into `Unknown variable` issues even with very simple policies. Here is what my policy looks like

```
package test.policy

import input

match[policy.name] {
   policies := data.policies[input.PolicyBaseMsg.TenantId]
   policy := policies[_]
   policy.name == input.name
}

```

This policy uses the standard constructs of `input` and `data` from `rego`. I have the following 2 files

**data.json**
```
{"policies": {"d66688a0-214a-4bdc-aceb-389ccc956e56": {"Policy_1": {"name": "Talha"}}}}
```
**input.json**
```
{"name":"Talha", "PolicyBaseMsg": {"TenantId":  "d66688a0-214a-4bdc-aceb-389ccc956e56"}}
```

Now I am loading all this into fregot in the following way

```
fregot repl --watch
F u g u e   R E G O   T o o l k i t
fregot v0.12.0 repl - use :help for usage info
repl% 


repl% :load data.json 
Loading data.json...
OK


repl% :input input.json 
repl% 



repl% :load test.rego
Loading test.rego...
Loaded package test.policy



test.policy% match
fregot (eval error):
  "test.rego" (line 11, column 9):
  unknown variable:

    11| match [[policy.name, policy.responses]]  {
                ^^^^^^^^^^^

  Unknown variable: policy_0

  Stack trace:
    rule test.policy.match at match:1:1
test.policy% 

```

Note that fregot is complaining about some unfamiliar variable `policy_0`

```
 Unknown variable: policy_0
```

There is no such variable in the entire rego policy. What might be happening here? 
This policy run perfectly fine with normal OPA/Rego tools.

**Comment by jaspervdj-luminal** [comment]
Thanks for reporting this @ahmedtalhakhan!  This was definitely a bug on our side.  I'll do a release shortly.
