### ISSUE TITLE
Load a directory in repl

### ISSUE THREAD

**Issue by snuggie12** [fugue/fregot#280]
Is this possible? I don't see anything in `:help` but could be missing something.

If it doesn't exist, could it?

PS You all are heroes. Thanks for making this.

**Comment by jaspervdj-luminal** [comment]
There's currently no command to load an entire directory, but you can pass directories as arguments to fregot -- e.g. `fregot repl dir1 dir2 file1.rego`.  Does that help with your use case?

**Comment by snuggie12** [comment]
I think so. Does passing a directory load all the files in there?

**Comment by jaspervdj-luminal** [comment]
Yes, it does a recursive search in the directory to find all `.rego` files in there.

**Comment by snuggie12** [comment]
It didn't work for me. I still had to do a `:load relative/path/to/foo.rego`

Here's my output (alias'd `fregot` as I kept forgetting the name):
```
$ opa-debugger repl lib required-labels-combined
F u g u e   R E G O   T o o l k i t
fregot v0.13.3 repl - use :help for usage info
repl% :break test_labels_missing_ct
Set breakpoint at repl.test_labels_missing_ct
repl% test_labels_missing_ct
fregot (compile error):
  "test_labels_missing_ct" (line 1, column 1):
  unknown variable:

    1| test_labels_missing_ct
       ^^^^^^^^^^^^^^^^^^^^^^

  Undefined variable: test_labels_missing_ct
```

**Comment by jaspervdj-luminal** [comment]
In which package is `test_labels_missing_ct` defined?  There should be a line at the top of the file like `package some_package`.  You probably want to do something along the lines of:

```
:break some_package.test_labels_missing_ct
data.some_package.test_labels_missing_ct
```

**Note** the `data.` in the second line -- everything in Rego is nested under the data document.

Alternatively, `fregot` allows you to navigate to the package so you don't have to repeat that part:

```
:open some_package
:break test_labels_missing_ct
test_labels_missing_ct
```

**Comment by snuggie12** [comment]
Perfect, that worked.

Previously I just did a `:load` in dependency order so the package was in the last file loaded (my `src_test.rego`). I suppose the package is sort of auto-opened?

Anyways, I did an `:open` just as you said and all worked fine. Thanks so much!
